project:
  type: website
  output-dir: docs

website:
  title: "adrinnnagy.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: text-analysis.qmd
        text: Text Analysis
      - href: maps.qmd
        text: Maps

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true



